CREATE DATABASE `court` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE court;

DROP TABLE IF EXISTS `bops_user`;
CREATE TABLE `bops_user`(
	 `ID` 				BIGINT NOT NULL AUTO_INCREMENT,
	 `GMT_CREATE` 		DATETIME  NOT NULL,
	 `GMT_MODIFIED` 	DATETIME  NOT NULL,
	 `STATUS`			INT NOT NULL COMMENT '可用0,不可用1',
	 `ACCOUNT` 			VARCHAR(64) NOT NULL UNIQUE COMMENT '登陆账号',
	 `NAME` 			VARCHAR(16) COMMENT '名字',
	 `PASSWORD`  		VARCHAR(64) NOT NULL COMMENT '密码',
	 `USER_TYPE`		VARCHAR(8)   COMMENT '用户类型',
	 PRIMARY KEY  (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO bops_user(GMT_CREATE, GMT_MODIFIED, STATUS,ACCOUNT, NAME, PASSWORD) VALUES(now(), now(), 0, 'admin','admin', '496705');

